import React,{useEffect,useRef,useState}from'react';
import L from'leaflet';import'leaflet/dist/leaflet.css';
import api from'../../api/trailerDepartment';import{Card,Empty,PageHeader,Status,useLoad}from'./TrailerUi';
const CENTER=[39.5,-98.35];const COLORS={available:'#16a34a',rented:'#2563eb',maintenance:'#d97706',under_inspection:'#7c3aed',out_of_service:'#dc2626',held_damage:'#be123c',unknown:'#64748b'};
function escape(value){return String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
export default function TrailerMapPage(){const mapNode=useRef(null),mapRef=useRef(null),layerRef=useRef(null);const[q,setQ]=useState('');const{data,loading,error,reload}=useLoad(()=>api.mapData(),[]);const rows=(data?.trailers||[]).filter((r)=>!q||[r.unit_number,r.current_company_name,r.physical_status].some((v)=>String(v||'').toLowerCase().includes(q.toLowerCase())));
useEffect(()=>{if(!mapNode.current||mapRef.current)return;mapRef.current=L.map(mapNode.current).setView(CENTER,4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(mapRef.current);layerRef.current=L.layerGroup().addTo(mapRef.current);return()=>{mapRef.current?.remove();mapRef.current=null}},[]);
useEffect(()=>{const layer=layerRef.current;if(!layer)return;layer.clearLayers();const points=[];for(const row of rows){if(row.current_lat==null||row.current_lng==null)continue;const lat=Number(row.current_lat),lng=Number(row.current_lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))continue;points.push([lat,lng]);L.circleMarker([lat,lng],{radius:8,color:'#fff',weight:2,fillColor:COLORS[row.physical_status]||COLORS.unknown,fillOpacity:1}).bindPopup(`<b>Trailer ${escape(row.unit_number)}</b><br>${escape(row.physical_status).replaceAll('_',' ')}<br>${escape(row.current_location_text||'Location unavailable')}<br><small>Source: ${escape(row.location_source||'unknown')}</small>`).addTo(layer)}if(points.length&&mapRef.current)mapRef.current.fitBounds(points,{padding:[24,24],maxZoom:12})},[rows]);
return <div><PageHeader title="Trailer Map" subtitle="Trailer assets only. Driver-derived positions are labeled and are not live trailer GPS." actions={<button className="btn btn-secondary" onClick={reload}>Refresh</button>}/><label className="trailer-search">Search trailers<input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Unit, renter, or status"/></label>{error&&<div className="alert alert-danger">{error}</div>}<div className="trailer-map-layout"><div ref={mapNode} className="trailer-map" role="application" aria-label="Trailer locations"/><Card className="trailer-map-list"><h3>All trailers ({rows.length})</h3>{loading?<div className="loading">Loading…</div>:!rows.length?<Empty/>:rows.map((row)=><div className="trailer-map-row" key={row.id}><b>{row.unit_number}</b><Status value={row.physical_status}/><span>{row.current_location_text||'No coordinates'}</span><small>{row.location_source==='derived_from_driver'?'Derived from driver — not trailer GPS':row.location_source||'Unknown source'}</small></div>)}</Card></div></div>}
