/**
 * UI-chrome strings for the public /questions page in uz/ru/en.
 * Question/answer/result CONTENT comes from the server; these are only the
 * interface texts (buttons, labels, validation, progress).
 */

export const SOS_LANGS = [
  { key: "uz", label: "Oʻzbekcha" },
  { key: "ru", label: "Русский" },
  { key: "en", label: "English" },
];

export const STRINGS = {
  uz: {
    appTitle: "Savol Ortidagi Savol",
    appAbbr: "SOS",
    testBadge: "TEST rejimi",
    testNote: "Bu sinov sahifasi — javoblaringiz haqiqiy natijalarga qoʻshilmaydi.",
    welcomeTitle: "Jamoaviy oʻyin-soʻrovnomasiga xush kelibsiz!",
    welcomeText: "Bu qisqa soʻrovnoma ish jarayonidagi vaziyatlarga birinchi munosabatingizni aniqlashga yordam beradi. 10 ta savol, taxminan 5 daqiqa. Toʻgʻri yoki notoʻgʻri javob yoʻq — oʻzingizga eng yaqin variantni tanlang.",
    welcomePrivacy: "Shaxsiy natijangizni faqat oʻzingiz va administratorlar koʻradi. Umumiy ekranda faqat anonim jamoaviy natijalar chiqadi.",
    chooseLanguage: "Tilni tanlang",
    start: "Boshlash",
    viewMyResult: "Mening natijamni koʻrish",
    detailsTitle: "Oʻzingiz haqingizda",
    fullName: "Toʻliq ism-familiya",
    fullNamePlaceholder: "Masalan: Aziz Karimov",
    department: "Boʻlim",
    departmentPlaceholder: "Boʻlimni tanlang",
    dispatchTeam: "Dispetcherlik jamoasi",
    dispatchTeamPlaceholder: "Jamoangizni tanlang",
    nameRequired: "Iltimos, toʻliq ism-familiyangizni kiriting (kamida 3 ta harf).",
    departmentRequired: "Iltimos, boʻlimingizni tanlang.",
    teamRequired: "Iltimos, dispetcherlik jamoangizni tanlang.",
    continue: "Davom etish",
    back: "Orqaga",
    next: "Keyingisi",
    progress: (i, n) => `${i} / ${n}`,
    answerRequired: "Iltimos, variantlardan birini tanlang.",
    reviewTitle: "Yakuniy tekshiruv",
    reviewText: "Barcha 10 ta savolga javob berdingiz. Javoblaringizni yubormoqchimisiz? Yuborishdan oldin orqaga qaytib, javoblarni oʻzgartirishingiz mumkin.",
    submit: "Javoblarni yuborish",
    submitting: "Yuborilmoqda…",
    duplicateTitle: "Bu ism allaqachon roʻyxatda bor",
    duplicateText: "Xuddi shu ism va boʻlim bilan javob allaqachon topshirilgan. Agar bu siz boʻlsangiz va qayta topshirmoqchi boʻlsangiz, davom eting — administrator ikkala javobni koʻrib chiqadi.",
    duplicateContinue: "Baribir yuborish",
    duplicateCancel: "Bekor qilish",
    closedTitle: "Soʻrovnoma yopilgan",
    closedText: "Hozircha javob qabul qilinmaydi. Iltimos, tadbir tashkilotchisiga murojaat qiling.",
    staleTitle: "Soʻrovnoma yangilandi",
    staleText: "Savollar yangilangan koʻrinadi. Iltimos, sahifani yangilang va qaytadan boshlang.",
    reload: "Sahifani yangilash",
    errorTitle: "Xatolik yuz berdi",
    retry: "Qayta urinish",
    resultTitle: "Sizning shaxsiy natijangiz",
    resultIntro: "Javoblaringiz asosida birinchi reaksiya moyilligingiz quyidagicha koʻrinadi:",
    scoresTitle: "Ballar taqsimoti",
    done: "Tayyor",
    loading: "Yuklanmoqda…",
  },
  ru: {
    appTitle: "Savol Ortidagi Savol",
    appAbbr: "SOS",
    testBadge: "ТЕСТ-режим",
    testNote: "Это тестовая страница — ваши ответы не попадут в настоящие результаты.",
    welcomeTitle: "Добро пожаловать в командный опрос!",
    welcomeText: "Этот короткий опрос поможет увидеть вашу первую реакцию на рабочие ситуации. 10 вопросов, примерно 5 минут. Правильных и неправильных ответов нет — выбирайте вариант, который ближе всего к вам.",
    welcomePrivacy: "Ваш личный результат видите только вы и администраторы. На общем экране показываются только анонимные командные итоги.",
    chooseLanguage: "Выберите язык",
    start: "Начать",
    viewMyResult: "Посмотреть мой результат",
    detailsTitle: "О вас",
    fullName: "Фамилия и имя",
    fullNamePlaceholder: "Например: Азиз Каримов",
    department: "Отдел",
    departmentPlaceholder: "Выберите отдел",
    dispatchTeam: "Диспетчерская команда",
    dispatchTeamPlaceholder: "Выберите вашу команду",
    nameRequired: "Пожалуйста, введите фамилию и имя (не меньше 3 букв).",
    departmentRequired: "Пожалуйста, выберите ваш отдел.",
    teamRequired: "Пожалуйста, выберите вашу диспетчерскую команду.",
    continue: "Продолжить",
    back: "Назад",
    next: "Далее",
    progress: (i, n) => `${i} / ${n}`,
    answerRequired: "Пожалуйста, выберите один из вариантов.",
    reviewTitle: "Финальная проверка",
    reviewText: "Вы ответили на все 10 вопросов. Отправить ответы? Перед отправкой можно вернуться назад и изменить ответы.",
    submit: "Отправить ответы",
    submitting: "Отправляем…",
    duplicateTitle: "Это имя уже есть в списке",
    duplicateText: "Ответ с таким же именем и отделом уже отправлен. Если это вы и хотите пройти заново — продолжайте, администратор увидит обе записи.",
    duplicateContinue: "Всё равно отправить",
    duplicateCancel: "Отмена",
    closedTitle: "Опрос закрыт",
    closedText: "Приём ответов сейчас закрыт. Обратитесь к организатору мероприятия.",
    staleTitle: "Опрос обновился",
    staleText: "Похоже, вопросы обновились. Пожалуйста, обновите страницу и начните заново.",
    reload: "Обновить страницу",
    errorTitle: "Произошла ошибка",
    retry: "Повторить",
    resultTitle: "Ваш личный результат",
    resultIntro: "По вашим ответам склонность первой реакции выглядит так:",
    scoresTitle: "Распределение баллов",
    done: "Готово",
    loading: "Загрузка…",
  },
  en: {
    appTitle: "Savol Ortidagi Savol",
    appAbbr: "SOS",
    testBadge: "TEST mode",
    testNote: "This is a practice page — your answers will not be counted in the real results.",
    welcomeTitle: "Welcome to the team assessment!",
    welcomeText: "This short assessment helps you see your first reaction to everyday work situations. 10 questions, about 5 minutes. There are no right or wrong answers — pick the option closest to what you would really do.",
    welcomePrivacy: "Your personal result is visible only to you and the administrators. The shared screen shows anonymous team totals only.",
    chooseLanguage: "Choose your language",
    start: "Start",
    viewMyResult: "View my result",
    detailsTitle: "About you",
    fullName: "Full name",
    fullNamePlaceholder: "For example: Aziz Karimov",
    department: "Department",
    departmentPlaceholder: "Select your department",
    dispatchTeam: "Dispatch team",
    dispatchTeamPlaceholder: "Select your team",
    nameRequired: "Please enter your full name (at least 3 letters).",
    departmentRequired: "Please select your department.",
    teamRequired: "Please select your dispatch team.",
    continue: "Continue",
    back: "Back",
    next: "Next",
    progress: (i, n) => `${i} of ${n}`,
    answerRequired: "Please choose one of the options.",
    reviewTitle: "Final check",
    reviewText: "You have answered all 10 questions. Submit your answers? You can still go back and change them before submitting.",
    submit: "Submit answers",
    submitting: "Submitting…",
    duplicateTitle: "This name is already on the list",
    duplicateText: "An answer with the same name and department was already submitted. If that was you and you want to retake it, continue — the administrator will see both records.",
    duplicateContinue: "Submit anyway",
    duplicateCancel: "Cancel",
    closedTitle: "The questionnaire is closed",
    closedText: "Responses are not being accepted right now. Please contact the event organizer.",
    staleTitle: "The questionnaire was updated",
    staleText: "The questions appear to have been updated. Please reload the page and start again.",
    reload: "Reload page",
    errorTitle: "Something went wrong",
    retry: "Try again",
    resultTitle: "Your personal result",
    resultIntro: "Based on your answers, your first-reaction tendency looks like this:",
    scoresTitle: "Score breakdown",
    done: "Done",
    loading: "Loading…",
  },
};
