-- ─── Driver Location Monitoring — RETIRED, and no longer created here ────
-- The pickup/delivery "Checked In / Checked Out" location-monitor feature was
-- retired 2026-07 (poller, callback handlers, admin API/UI and DB module all
-- removed; see docs/architecture/retired-checkin-checkout-feature.md). Its two
-- tables — driver_location_monitors and driver_location_checkins, with their
-- indexes and constraints — used to be created here so a fresh init-db matched
-- production, and the note said they should be "dropped manually AFTER a backup
-- if the data is no longer needed".
--
-- That manual drop now has a home: Settings → Retired Leftovers. Which is
-- exactly why the CREATEs are gone. A baseline that recreates a droppable table
-- makes the drop non-durable: schema.sql runs verbatim on EVERY boot, so the
-- operator's confirmed deletion destroys the rows and then the empty tables
-- reappear at the next restart and are reported as leftovers again.
--
-- Removing a CREATE TABLE IF NOT EXISTS is not destructive. An existing
-- deployment keeps both tables and every row until an operator deliberately
-- drops them; a fresh install simply never creates them, which is correct
-- because no application code has referenced them since 2026-07.
--
-- This file stays (rather than being deleted) so the baseline segments remain
-- contiguously numbered — tests/schemaBaselineBuild.test.js asserts that — and
-- so the decision is recorded where the next person looks for it.
--
-- tests/retiredLeftovers.test.js asserts no droppable table is recreated here.
