-- Structural schema snapshot (generated by npm run db:docs).
-- Rebuilt from the live catalog: CREATE TABLE + constraints + indexes.
-- Contains NO row data. Do not edit by hand.
-- Generated from an introspected database (76 tables). Structure only — no row data.

-- ── Tables ──────────────────────────────────────────────────────────
CREATE TABLE admins (
  id serial NOT NULL,
  username text NOT NULL,
  password_hash text NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE ai_insights (
  id serial NOT NULL,
  report_id integer,
  kind character varying(32) NOT NULL,
  severity smallint DEFAULT 1,
  rank integer DEFAULT 0,
  title text NOT NULL,
  narrative_html text,
  suggested_action text,
  evidence_json jsonb,
  metrics_json jsonb,
  driver_name text,
  driver_telegram_id bigint,
  group_id integer,
  status character varying(16) DEFAULT 'pending'::character varying,
  admin_feedback text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE ai_reports (
  id serial NOT NULL,
  group_id integer,
  report_text text NOT NULL,
  report_type character varying(50) DEFAULT 'driver'::character varying NOT NULL,
  status character varying(20) DEFAULT 'draft'::character varying NOT NULL,
  generated_at timestamp without time zone DEFAULT now() NOT NULL,
  sent_at timestamp without time zone
);

CREATE TABLE bot_access_settings (
  id integer DEFAULT 1 NOT NULL,
  super_admin_telegram_id bigint,
  super_admin_label text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE bot_sent_messages (
  id bigserial NOT NULL,
  telegram_chat_id bigint NOT NULL,
  telegram_message_id bigint NOT NULL,
  sent_at timestamp with time zone,
  message_text text,
  content_kind text DEFAULT 'other'::text NOT NULL,
  source_method text,
  edited_at timestamp with time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  last_edit_text text
);

CREATE TABLE bot_users (
  telegram_user_id bigint NOT NULL,
  username text,
  first_name text,
  last_name text,
  interactions integer DEFAULT 0 NOT NULL,
  last_action text,
  last_group_id integer,
  first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  last_interaction_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_chat_id bigint,
  last_group_name text,
  language_code text,
  is_bot boolean DEFAULT false,
  message_count integer DEFAULT 0 NOT NULL,
  source text
);

CREATE TABLE broadcast_button_clicks (
  id serial NOT NULL,
  broadcast_id integer,
  button_index integer NOT NULL,
  button_label text,
  driver_telegram_id bigint NOT NULL,
  driver_username text,
  driver_first_name text,
  driver_last_name text,
  group_telegram_id bigint,
  group_name text,
  clicked_at timestamp without time zone DEFAULT now()
);

CREATE TABLE broadcast_deliveries (
  id serial NOT NULL,
  broadcast_id integer,
  group_id integer,
  telegram_group_id bigint,
  group_name text,
  status text DEFAULT 'sent'::text,
  error_message text,
  sent_at timestamp without time zone DEFAULT now()
);

CREATE TABLE broadcasts (
  id serial NOT NULL,
  type text DEFAULT 'regular'::text NOT NULL,
  message_text_en text,
  message_text_ru text,
  message_text_uz text,
  media_items jsonb,
  media_position text DEFAULT 'above'::text,
  parse_mode text DEFAULT 'HTML'::text,
  buttons jsonb,
  target_type text DEFAULT 'all'::text,
  target_driver_ids integer[],
  target_languages text[],
  force_language text,
  status text DEFAULT 'sent'::text,
  sent_at timestamp without time zone DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  target_active_filter text
);

CREATE TABLE chat_logs (
  id serial NOT NULL,
  group_id integer,
  telegram_user_id bigint,
  telegram_message_id bigint,
  sender_name text,
  message_text text NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE chat_message_annotations (
  chat_log_id integer NOT NULL,
  language character varying(8),
  intent character varying(32),
  sentiment smallint,
  urgency smallint,
  role_guess character varying(16),
  role_confidence smallint,
  is_acknowledgement boolean,
  toxic boolean,
  entities_json jsonb,
  model_version text,
  annotated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE datatruck_document_deliveries (
  id bigserial NOT NULL,
  signature text NOT NULL,
  order_id text,
  load_reference text,
  file_type text NOT NULL,
  file_link text,
  uploaded_by text,
  uploaded_at timestamp with time zone,
  driver_name text,
  unit_number text,
  matched_by text,
  group_id integer,
  telegram_group_id bigint,
  status text DEFAULT 'pending'::text NOT NULL,
  telegram_message_id bigint,
  attempt_count integer DEFAULT 0 NOT NULL,
  last_error text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE dispatch_eta_global_settings (
  id integer NOT NULL,
  driver_interval_minutes integer DEFAULT 60 NOT NULL,
  test_interval_minutes integer DEFAULT 60 NOT NULL,
  updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE dispatch_eta_updates (
  id serial NOT NULL,
  group_id integer NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  target_mode text DEFAULT 'driver'::text NOT NULL,
  interval_minutes integer DEFAULT 60 NOT NULL,
  next_run_at timestamp without time zone,
  processing boolean DEFAULT false NOT NULL,
  processing_started_at timestamp without time zone,
  last_run_at timestamp without time zone,
  last_status text,
  last_error text,
  last_pinned_signature text,
  cached_pickup text,
  cached_delivery text,
  cached_destination_query text,
  cached_context_json jsonb,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE dispatch_team_drivers (
  id serial NOT NULL,
  team_id integer NOT NULL,
  driver_external_id text,
  driver_normalized_name text NOT NULL,
  driver_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  driver_profile_id integer,
  group_id integer,
  unit_number text,
  active boolean DEFAULT true NOT NULL,
  needs_review boolean DEFAULT false NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE dispatch_team_members (
  id serial NOT NULL,
  team_id integer NOT NULL,
  name text,
  telegram_username text,
  telegram_user_id bigint,
  role text,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE dispatch_teams (
  id serial NOT NULL,
  name text NOT NULL,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE driver_home_status (
  group_id integer NOT NULL,
  telegram_group_id bigint,
  state text NOT NULL,
  state_since timestamp with time zone NOT NULL,
  last_status_text text,
  last_status_at timestamp with time zone NOT NULL,
  road_bonus_weeks_notified integer DEFAULT 0 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE driver_location_checkins (
  id serial NOT NULL,
  monitor_id integer NOT NULL,
  group_id integer NOT NULL,
  telegram_group_id bigint NOT NULL,
  order_id text,
  stop_type text NOT NULL,
  location_address text,
  appointment_at timestamp with time zone,
  eta_at timestamp with time zone,
  distance_miles_at_prompt numeric,
  prompt_message_id bigint,
  status text DEFAULT 'awaiting_response'::text NOT NULL,
  driver_response text,
  responded_by_username text,
  responded_by_user_id bigint,
  responded_at timestamp with time zone,
  on_time boolean,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  dedupe_key text,
  checked_in_at timestamp with time zone,
  checked_out_at timestamp with time zone,
  checked_in_by_username text,
  checked_in_by_user_id bigint,
  checked_out_by_username text,
  checked_out_by_user_id bigint
);

CREATE TABLE driver_location_monitors (
  id serial NOT NULL,
  group_id integer NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  interval_minutes integer DEFAULT 30 NOT NULL,
  checkin_radius_miles numeric DEFAULT 8 NOT NULL,
  next_run_at timestamp without time zone,
  processing boolean DEFAULT false NOT NULL,
  processing_started_at timestamp without time zone,
  last_run_at timestamp without time zone,
  last_status text,
  last_error text,
  current_order_id text,
  load_phase text,
  target_stop_type text,
  target_address text,
  target_lat double precision,
  target_lng double precision,
  target_appointment_at timestamp with time zone,
  last_eta_minutes integer,
  last_eta_at timestamp with time zone,
  last_distance_miles numeric,
  active_checkin_id integer,
  cached_context_json jsonb,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE driver_profiles (
  id serial NOT NULL,
  group_id integer NOT NULL,
  first_name text,
  last_name text,
  secondary_first_name text,
  secondary_last_name text,
  first_name_source text,
  last_name_source text,
  secondary_first_name_source text,
  secondary_last_name_source text,
  driver_type text,
  driver_type_source text,
  status text DEFAULT 'active'::text,
  unit_number text,
  unit_number_source text,
  language character varying(5) DEFAULT 'en'::character varying,
  date_of_birth date,
  date_of_start date,
  needs_review boolean DEFAULT false,
  backfill_confidence smallint,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  telegram_username text,
  telegram_user_id bigint
);

CREATE TABLE driver_road_history (
  id serial NOT NULL,
  group_id integer NOT NULL,
  driver_name text,
  unit_number text,
  road_started_at timestamp with time zone NOT NULL,
  home_arrived_at timestamp with time zone NOT NULL,
  days_on_road integer NOT NULL,
  exceeded_weeks integer DEFAULT 0 NOT NULL,
  bonus_usd numeric(10,2) DEFAULT 0 NOT NULL,
  bonus_posted_at timestamp with time zone,
  recorded_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE drivers (
  id serial NOT NULL,
  telegram_user_id bigint NOT NULL,
  username text,
  first_name text,
  last_name text,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE duplicate_unit_reports (
  id serial NOT NULL,
  unit_number text NOT NULL,
  report_type text NOT NULL,
  group_ids integer[] DEFAULT '{}'::integer[] NOT NULL,
  group_names text[] DEFAULT '{}'::text[] NOT NULL,
  group_driver_name text,
  provider text,
  provider_driver_name text,
  detail text,
  severity text DEFAULT 'info'::text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  resolved_at timestamp with time zone
);

CREATE TABLE eld_settings (
  id integer NOT NULL,
  samsara_enabled boolean DEFAULT true NOT NULL,
  samsara_api_key_encrypted text,
  drivehos_provider_key_encrypted text,
  drivehos_api_base text DEFAULT 'https://api.drivehos.app'::text NOT NULL,
  factor_enabled boolean DEFAULT true NOT NULL,
  factor_company_key_encrypted text,
  leader_enabled boolean DEFAULT true NOT NULL,
  leader_company_key_encrypted text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE employee_birthday_settings (
  id integer NOT NULL,
  timezone text DEFAULT 'Asia/Tashkent'::text NOT NULL,
  send_hour integer DEFAULT 0 NOT NULL,
  send_minute integer DEFAULT 0 NOT NULL,
  ai_instructions text DEFAULT 'Write a warm, professional birthday message for office staff at Wenze. Be sincere and appreciative. Use different wording each time.'::text NOT NULL,
  fallback_template text DEFAULT '🎉 <b>Happy Birthday!</b> 🎂

Today we celebrate: <b>{names}</b>!

Wishing you a fantastic day and a great year ahead!

— <i>Wenze Management</i>'::text NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE employee_birthdays (
  id serial NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  birthday date NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE employee_votes (
  id serial NOT NULL,
  poll_id integer,
  option_id integer,
  telegram_user_id bigint NOT NULL,
  telegram_username text,
  telegram_first_name text,
  unit_number text NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE employee_votes_options (
  id serial NOT NULL,
  poll_id integer,
  unit_number text NOT NULL,
  driver_name text,
  company_name text,
  driver_type text,
  group_id integer
);

CREATE TABLE employee_votes_polls (
  id serial NOT NULL,
  question text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  telegram_message_id bigint,
  telegram_chat_id bigint,
  status text DEFAULT 'active'::text
);

CREATE TABLE facebook_connect_sessions (
  id serial NOT NULL,
  session_token text NOT NULL,
  group_id integer NOT NULL,
  telegram_group_id bigint NOT NULL,
  group_name text,
  requested_by_telegram_user_id bigint,
  requested_by_name text,
  status text DEFAULT 'pending'::text NOT NULL,
  oauth_state text,
  oauth_user_access_token_encrypted text,
  oauth_user_id text,
  oauth_user_name text,
  expires_at timestamp without time zone NOT NULL,
  last_error text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone
);

CREATE TABLE facebook_lead_auto_message_rules (
  id serial NOT NULL,
  settings_id integer NOT NULL,
  label text DEFAULT 'Rule'::text NOT NULL,
  days_of_week smallint[] DEFAULT '{1,2,3,4,5}'::smallint[] NOT NULL,
  start_time_local time without time zone NOT NULL,
  end_time_local time without time zone NOT NULL,
  message_template text DEFAULT ''::text NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE facebook_lead_auto_message_settings (
  id serial NOT NULL,
  timezone text DEFAULT 'America/Chicago'::text NOT NULL,
  is_enabled boolean DEFAULT true NOT NULL,
  rep_name text DEFAULT 'Tom'::text NOT NULL,
  company_name text DEFAULT 'Wenze trucking company'::text NOT NULL,
  position_label text DEFAULT 'OTR position'::text NOT NULL,
  fallback_template text DEFAULT ''::text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE facebook_lead_sms_mirrors (
  id serial NOT NULL,
  telegram_chat_id bigint NOT NULL,
  telegram_message_id bigint NOT NULL,
  driver_phone text NOT NULL,
  sms_body text NOT NULL,
  lead_name text,
  page_id text,
  rule_label text,
  ringcentral_message_id text,
  source_type text DEFAULT 'outbound_auto'::text NOT NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE facebook_page_connections (
  id serial NOT NULL,
  group_id integer NOT NULL,
  telegram_group_id bigint NOT NULL,
  group_name text,
  page_id text NOT NULL,
  page_name text NOT NULL,
  access_token_encrypted text NOT NULL,
  token_last4 text,
  connected_by_facebook_user_id text,
  connected_by_facebook_user_name text,
  granted_tasks text[] DEFAULT '{}'::text[],
  granted_scopes text[] DEFAULT '{}'::text[],
  subscribed_fields text[] DEFAULT '{}'::text[],
  is_active boolean DEFAULT true NOT NULL,
  last_subscription_status text,
  last_error text,
  connected_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE facebook_seen_senders (
  page_id text NOT NULL,
  sender_id text NOT NULL,
  first_event_key text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE facebook_webhook_events (
  id serial NOT NULL,
  event_key text NOT NULL,
  page_id text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  attempt_count integer DEFAULT 0 NOT NULL,
  next_retry_at timestamp without time zone DEFAULT now() NOT NULL,
  last_error text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  processed_at timestamp without time zone
);

CREATE TABLE fuel_monitor_inbox (
  id serial NOT NULL,
  group_id integer NOT NULL,
  telegram_group_id bigint NOT NULL,
  message_id bigint NOT NULL,
  message_text text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  alert_id integer,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  processed_at timestamp without time zone
);

CREATE TABLE fuel_stop_alerts (
  id serial NOT NULL,
  group_id integer NOT NULL,
  telegram_group_id bigint NOT NULL,
  source_message_id bigint NOT NULL,
  station_name text,
  station_address text,
  station_lat double precision NOT NULL,
  station_lng double precision NOT NULL,
  radius_miles double precision DEFAULT 10 NOT NULL,
  status text DEFAULT 'watching'::text NOT NULL,
  processing boolean DEFAULT false NOT NULL,
  processing_started_at timestamp without time zone,
  last_distance_miles double precision,
  last_checked_at timestamp without time zone,
  notified_at timestamp without time zone,
  last_error text,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  expires_at timestamp without time zone,
  next_check_at timestamp without time zone,
  eta_minutes double precision,
  eta_boundary_at timestamp without time zone
);

CREATE TABLE gmaps_settings (
  id integer NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  server_api_key_encrypted text,
  routes_api_enabled boolean DEFAULT true NOT NULL,
  roads_api_enabled boolean DEFAULT false NOT NULL,
  geocoding_api_enabled boolean DEFAULT false NOT NULL,
  geocoding_api_key_encrypted text,
  deviation_threshold_meters integer DEFAULT 250 NOT NULL,
  check_interval_seconds integer DEFAULT 300 NOT NULL,
  off_route_grace_checks integer DEFAULT 3 NOT NULL,
  warning_cooldown_minutes integer DEFAULT 30 NOT NULL,
  stale_gps_minutes integer DEFAULT 15 NOT NULL,
  parked_speed_mph integer DEFAULT 5 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE group_members (
  group_id integer NOT NULL,
  telegram_user_id bigint NOT NULL,
  username text,
  first_name text,
  last_name text,
  last_seen_at timestamp with time zone DEFAULT now()
);

CREATE TABLE group_pinned_messages (
  id serial NOT NULL,
  group_id integer NOT NULL,
  telegram_group_id bigint NOT NULL,
  pinned_message_id bigint NOT NULL,
  pinned_message_json jsonb NOT NULL,
  source_event_message_id bigint,
  source_event_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE group_recent_loads (
  id serial NOT NULL,
  group_id integer NOT NULL,
  telegram_message_id bigint NOT NULL,
  source_message_at timestamp with time zone,
  context_signature text NOT NULL,
  pickup_summary text DEFAULT ''::text NOT NULL,
  delivery_summary text DEFAULT ''::text NOT NULL,
  destination_query text DEFAULT ''::text NOT NULL,
  pickup_window_start timestamp with time zone,
  pickup_window_end timestamp with time zone,
  delivery_window_start timestamp with time zone,
  delivery_window_end timestamp with time zone,
  load_identifier text,
  caption_preview text,
  extracted_raw_json jsonb,
  ai_model text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE groups (
  id serial NOT NULL,
  telegram_group_id bigint NOT NULL,
  group_name text,
  language character varying(5) DEFAULT 'en'::character varying,
  group_type text DEFAULT 'driver'::text,
  created_at timestamp without time zone DEFAULT now(),
  active boolean DEFAULT true,
  driver_birthday date,
  samsara_vehicle_id text,
  status_source text,
  status_updated_at timestamp without time zone,
  last_message_seen_at timestamp with time zone,
  bot_member_status text,
  bot_access_checked_at timestamp with time zone
);

CREATE TABLE home_time_requests (
  id serial NOT NULL,
  group_id integer,
  telegram_group_id bigint,
  driver_name text,
  unit_number text,
  requested_by_user_id bigint,
  requested_by_username text,
  requested_at timestamp with time zone DEFAULT now() NOT NULL,
  road_started_at timestamp with time zone,
  days_on_road integer,
  policy_met boolean,
  home_from date,
  home_to date,
  status text DEFAULT 'pending'::text NOT NULL,
  source text DEFAULT 'telegram'::text NOT NULL,
  ai_reasoning text,
  telegram_chat_id bigint,
  telegram_message_id bigint,
  decided_by_username text,
  decided_by_user_id bigint,
  decided_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE home_time_settings (
  id integer DEFAULT 1 NOT NULL,
  enabled boolean DEFAULT true NOT NULL,
  road_allowance_weeks integer DEFAULT 4 NOT NULL,
  home_allowance_days integer DEFAULT 4 NOT NULL,
  bonus_per_week numeric(10,2) DEFAULT 100 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE leads (
  id serial NOT NULL,
  source text NOT NULL,
  external_id text,
  full_name text,
  email text,
  phone text,
  job_title text,
  message text,
  bitrix_id text,
  bitrix_status text DEFAULT 'pending'::text,
  raw jsonb,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE message_group_settings (
  id integer NOT NULL,
  mileage_bonus_group_id text,
  road_bonus_group_id text,
  dispatch_review_group_id text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE mileage_bonus_notifications (
  id serial NOT NULL,
  driver_external_id text,
  driver_normalized_name text NOT NULL,
  driver_name text NOT NULL,
  threshold_miles integer NOT NULL,
  bonus_amount integer NOT NULL,
  miles_at_notification numeric(12,2) NOT NULL,
  period_start date,
  period_end date,
  trigger text DEFAULT 'scheduled'::text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  telegram_chat_id bigint,
  telegram_message_id bigint,
  telegram_followup_message_id bigint,
  decided_by_username text,
  decided_by_user_id bigint,
  decided_at timestamp without time zone,
  disregarded_by_username text,
  disregarded_at timestamp with time zone,
  resend_count integer DEFAULT 0 NOT NULL,
  last_resent_at timestamp with time zone,
  last_resent_by_username text,
  delivery_state text DEFAULT 'pending'::text NOT NULL,
  delivery_started_at timestamp with time zone DEFAULT now() NOT NULL,
  action_state text DEFAULT 'idle'::text NOT NULL,
  action_started_at timestamp with time zone,
  last_action_error text,
  telegram_deleted_at timestamp with time zone,
  telegram_delete_error text,
  created_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE mileage_bonus_progress (
  id serial NOT NULL,
  driver_external_id text,
  driver_normalized_name text NOT NULL,
  driver_name text NOT NULL,
  driver_type text,
  hire_date date,
  period_start date,
  period_end date,
  total_miles numeric(12,2) DEFAULT 0 NOT NULL,
  trips integer DEFAULT 0 NOT NULL,
  highest_tier_reached integer,
  next_tier integer,
  miles_to_next_tier numeric(12,2),
  is_active boolean DEFAULT true NOT NULL,
  activation_updated_at timestamp with time zone,
  activation_updated_by text,
  updated_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE mileage_bonus_runs (
  id bigserial NOT NULL,
  run_key text NOT NULL,
  trigger text NOT NULL,
  mode text NOT NULL,
  status text DEFAULT 'running'::text NOT NULL,
  attempt_count integer DEFAULT 1 NOT NULL,
  requested_by text,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  lease_expires_at timestamp with time zone NOT NULL,
  next_retry_at timestamp with time zone,
  finished_at timestamp with time zone,
  error text,
  summary jsonb
);

CREATE TABLE option_translations (
  id serial NOT NULL,
  option_id integer,
  language character varying(5) NOT NULL,
  option_text text NOT NULL
);

CREATE TABLE options (
  id serial NOT NULL,
  question_id integer,
  option_order integer NOT NULL
);

CREATE TABLE question_media (
  id serial NOT NULL,
  question_id integer,
  file_id text NOT NULL,
  media_type text NOT NULL,
  sort_order integer DEFAULT 0
);

CREATE TABLE question_translations (
  id serial NOT NULL,
  question_id integer,
  language character varying(5) NOT NULL,
  question_text text NOT NULL
);

CREATE TABLE questions (
  id serial NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  active boolean DEFAULT true,
  media_position text DEFAULT 'above'::text
);

CREATE TABLE raise_otp (
  id serial NOT NULL,
  round_id integer NOT NULL,
  team_id integer,
  contact text NOT NULL,
  contact_type text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  verified boolean DEFAULT false NOT NULL,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE raise_round_picks (
  id serial NOT NULL,
  submission_id integer NOT NULL,
  round_id integer NOT NULL,
  team_id integer NOT NULL,
  driver_normalized_name text NOT NULL,
  driver_name text NOT NULL,
  qualified boolean NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE raise_round_submissions (
  id serial NOT NULL,
  round_id integer NOT NULL,
  team_id integer NOT NULL,
  dispatcher_name text NOT NULL,
  dispatcher_contact text NOT NULL,
  contact_type text NOT NULL,
  submitted_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE raise_rounds (
  id serial NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  access_token text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  rate_low numeric(5,3) DEFAULT 0.720 NOT NULL,
  rate_high numeric(5,3) DEFAULT 0.750 NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  employee_chat_id text,
  employee_message_id bigint,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  closed_at timestamp with time zone
);

CREATE TABLE raise_settings (
  id integer NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  otp_channel text DEFAULT 'gmail'::text NOT NULL,
  schedule_enabled boolean DEFAULT false NOT NULL,
  weekly_day_of_week integer DEFAULT 7 NOT NULL,
  weekly_time_local text DEFAULT '14:00'::text NOT NULL,
  schedule_timezone text DEFAULT 'America/Chicago'::text NOT NULL,
  rate_low numeric(5,3) DEFAULT 0.720 NOT NULL,
  rate_high numeric(5,3) DEFAULT 0.750 NOT NULL,
  link_ttl_hours integer DEFAULT 48 NOT NULL,
  gmail_user text,
  gmail_app_password_encrypted text,
  next_run_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE recruiters (
  id serial NOT NULL,
  name text NOT NULL,
  phone_number text NOT NULL,
  phone_number_normalized text NOT NULL,
  active boolean DEFAULT true NOT NULL,
  jwt_token_encrypted text,
  client_id_encrypted text,
  client_secret_encrypted text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE responses (
  id serial NOT NULL,
  driver_id integer,
  group_id integer,
  question_id integer,
  option_id integer,
  answered_at timestamp without time zone DEFAULT now()
);

CREATE TABLE ringcentral_calls (
  id text NOT NULL,
  session_id text,
  recruiter_id integer,
  recruiter_number_normalized text,
  direction text,
  result text,
  from_number text,
  to_number text,
  duration_seconds integer DEFAULT 0 NOT NULL,
  call_time timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ringcentral_settings (
  id integer NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  api_base text DEFAULT 'https://platform.ringcentral.com'::text NOT NULL,
  client_id_encrypted text,
  client_secret_encrypted text,
  jwt_token_encrypted text,
  poll_minutes integer DEFAULT 10 NOT NULL,
  timezone text DEFAULT 'America/Chicago'::text NOT NULL,
  non_valuable_max_seconds integer DEFAULT 30 NOT NULL,
  real_conversation_min_seconds integer DEFAULT 60 NOT NULL,
  strong_conversation_min_seconds integer DEFAULT 180 NOT NULL,
  target_outbound integer DEFAULT 150 NOT NULL,
  target_real_conversations integer DEFAULT 35 NOT NULL,
  last_synced_at timestamp with time zone,
  last_sync_error text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE route_assignments (
  id serial NOT NULL,
  group_id integer,
  driver_profile_id integer,
  driver_label text,
  unit_number text,
  original_url text NOT NULL,
  origin_text text,
  destination_text text,
  waypoints jsonb DEFAULT '[]'::jsonb NOT NULL,
  origin_lat double precision,
  origin_lng double precision,
  destination_lat double precision,
  destination_lng double precision,
  encoded_polyline text,
  distance_meters double precision,
  duration_seconds double precision,
  status text DEFAULT 'active'::text NOT NULL,
  assigned_by text,
  last_checked_at timestamp with time zone,
  last_latitude double precision,
  last_longitude double precision,
  last_deviation_meters double precision,
  last_check_result text,
  consecutive_off_route integer DEFAULT 0 NOT NULL,
  last_notification_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  source text DEFAULT 'admin'::text NOT NULL,
  assigned_by_user_id bigint,
  telegram_chat_id bigint,
  telegram_message_id bigint
);

CREATE TABLE route_monitor_events (
  id serial NOT NULL,
  assignment_id integer NOT NULL,
  event_type text NOT NULL,
  result text,
  latitude double precision,
  longitude double precision,
  deviation_meters double precision,
  detail text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE safety_event_music_assets (
  id serial NOT NULL,
  name text NOT NULL,
  description text,
  mime_type text NOT NULL,
  file_size_bytes bigint NOT NULL,
  duration_seconds numeric(10,3),
  storage_kind text DEFAULT 'db_bytea'::text NOT NULL,
  file_data bytea,
  storage_path text,
  checksum_sha256 text,
  is_active boolean DEFAULT false NOT NULL,
  uploaded_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE safety_event_video_jobs (
  id bigserial NOT NULL,
  samsara_event_id text,
  telegram_group_id bigint,
  music_asset_id integer,
  status text DEFAULT 'pending'::text NOT NULL,
  video_source text,
  video_reference text,
  video_duration_seconds numeric(10,3),
  music_trim_mode text,
  error_message text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  started_at timestamp with time zone,
  finished_at timestamp with time zone
);

CREATE TABLE safety_event_video_settings (
  id integer NOT NULL,
  driver_group_music_enabled boolean DEFAULT false NOT NULL,
  speeding_music_enabled boolean DEFAULT true NOT NULL,
  active_music_asset_id integer,
  samsara_notification_group_original_video_enabled boolean DEFAULT true NOT NULL,
  music_volume numeric(4,2) DEFAULT 0.35 NOT NULL,
  preserve_original_audio boolean DEFAULT true NOT NULL,
  fade_in_seconds numeric(5,2) DEFAULT 0 NOT NULL,
  fade_out_seconds numeric(5,2) DEFAULT 1.50 NOT NULL,
  loop_music_when_video_longer boolean DEFAULT true NOT NULL,
  max_video_seconds integer DEFAULT 120 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE samsara_event_deliveries (
  event_id character varying(255) NOT NULL,
  target_chat_id character varying(255) NOT NULL,
  status character varying(32) DEFAULT 'delivered'::character varying NOT NULL,
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE samsara_poll_state (
  key character varying(120) NOT NULL,
  value text,
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE samsara_processed_events (
  id character varying(255) NOT NULL,
  processed_at timestamp without time zone DEFAULT now()
);

CREATE TABLE scheduled_messages (
  id serial NOT NULL,
  message_text_en text,
  message_text_ru text,
  message_text_uz text,
  media_items jsonb,
  media_file_id text,
  media_type text,
  media_position text DEFAULT 'above'::text,
  target_type text DEFAULT 'all'::text,
  target_driver_ids integer[],
  target_languages text[],
  force_language text,
  scheduled_at timestamp without time zone NOT NULL,
  schedule_type text DEFAULT 'one_time'::text,
  schedule_timezone text DEFAULT 'America/Chicago'::text,
  weekly_day_of_week smallint,
  weekly_time_local text,
  last_sent_at timestamp without time zone,
  last_run_status text,
  status text DEFAULT 'pending'::text,
  created_at timestamp without time zone DEFAULT now(),
  target_active_filter text
);

CREATE TABLE sender_role_consensus (
  group_id integer NOT NULL,
  telegram_user_id bigint NOT NULL,
  sender_name text,
  role character varying(16),
  confidence smallint,
  message_count integer,
  last_updated timestamp without time zone DEFAULT now()
);

CREATE TABLE service_runs (
  id serial NOT NULL,
  service_name text NOT NULL,
  run_key text NOT NULL,
  ran_at timestamp without time zone DEFAULT now() NOT NULL
);

-- ── Keys/uniques/checks (added before FKs so FK targets exist) ──────
ALTER TABLE admins ADD CONSTRAINT admins_pkey PRIMARY KEY (id);
ALTER TABLE admins ADD CONSTRAINT admins_username_key UNIQUE (username);
ALTER TABLE ai_insights ADD CONSTRAINT ai_insights_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'dismissed'::character varying, 'edited'::character varying, 'sent'::character varying])::text[])));
ALTER TABLE ai_insights ADD CONSTRAINT ai_insights_pkey PRIMARY KEY (id);
ALTER TABLE ai_reports ADD CONSTRAINT ai_reports_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'sent'::character varying, 'discarded'::character varying])::text[])));
ALTER TABLE ai_reports ADD CONSTRAINT ai_reports_type_check CHECK (((report_type)::text = ANY ((ARRAY['driver'::character varying, 'company'::character varying])::text[])));
ALTER TABLE ai_reports ADD CONSTRAINT ai_reports_pkey PRIMARY KEY (id);
ALTER TABLE bot_access_settings ADD CONSTRAINT bot_access_settings_id_check CHECK ((id = 1));
ALTER TABLE bot_access_settings ADD CONSTRAINT bot_access_settings_pkey PRIMARY KEY (id);
ALTER TABLE bot_sent_messages ADD CONSTRAINT bot_sent_messages_pkey PRIMARY KEY (id);
ALTER TABLE bot_sent_messages ADD CONSTRAINT bot_sent_messages_telegram_chat_id_telegram_message_id_key UNIQUE (telegram_chat_id, telegram_message_id);
ALTER TABLE bot_users ADD CONSTRAINT bot_users_pkey PRIMARY KEY (telegram_user_id);
ALTER TABLE broadcast_button_clicks ADD CONSTRAINT broadcast_button_clicks_pkey PRIMARY KEY (id);
ALTER TABLE broadcast_button_clicks ADD CONSTRAINT broadcast_button_clicks_broadcast_id_button_index_driver_te_key UNIQUE (broadcast_id, button_index, driver_telegram_id);
ALTER TABLE broadcast_deliveries ADD CONSTRAINT broadcast_deliveries_pkey PRIMARY KEY (id);
ALTER TABLE broadcasts ADD CONSTRAINT broadcasts_pkey PRIMARY KEY (id);
ALTER TABLE chat_logs ADD CONSTRAINT chat_logs_pkey PRIMARY KEY (id);
ALTER TABLE chat_message_annotations ADD CONSTRAINT chat_message_annotations_pkey PRIMARY KEY (chat_log_id);
ALTER TABLE datatruck_document_deliveries ADD CONSTRAINT datatruck_document_deliveries_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'suppressed_backfill'::text, 'skipped_no_group'::text])));
ALTER TABLE datatruck_document_deliveries ADD CONSTRAINT datatruck_document_deliveries_pkey PRIMARY KEY (id);
ALTER TABLE datatruck_document_deliveries ADD CONSTRAINT datatruck_document_deliveries_signature_key UNIQUE (signature);
ALTER TABLE dispatch_eta_global_settings ADD CONSTRAINT dispatch_eta_global_intervals_check CHECK ((((driver_interval_minutes >= 1) AND (driver_interval_minutes <= 1440)) AND ((test_interval_minutes >= 1) AND (test_interval_minutes <= 1440))));
ALTER TABLE dispatch_eta_global_settings ADD CONSTRAINT dispatch_eta_global_settings_id_check CHECK ((id = 1));
ALTER TABLE dispatch_eta_global_settings ADD CONSTRAINT dispatch_eta_global_settings_pkey PRIMARY KEY (id);
ALTER TABLE dispatch_eta_updates ADD CONSTRAINT dispatch_eta_interval_check CHECK (((interval_minutes >= 1) AND (interval_minutes <= 1440)));
ALTER TABLE dispatch_eta_updates ADD CONSTRAINT dispatch_eta_target_mode_check CHECK ((target_mode = ANY (ARRAY['driver'::text, 'test'::text])));
ALTER TABLE dispatch_eta_updates ADD CONSTRAINT dispatch_eta_updates_pkey PRIMARY KEY (id);
ALTER TABLE dispatch_eta_updates ADD CONSTRAINT dispatch_eta_updates_group_id_key UNIQUE (group_id);
ALTER TABLE dispatch_team_drivers ADD CONSTRAINT dispatch_team_drivers_pkey PRIMARY KEY (id);
ALTER TABLE dispatch_team_drivers ADD CONSTRAINT dispatch_team_drivers_team_id_driver_normalized_name_key UNIQUE (team_id, driver_normalized_name);
ALTER TABLE dispatch_team_members ADD CONSTRAINT dispatch_team_members_role_check CHECK (((role IS NULL) OR (role = ANY (ARRAY['dispatcher'::text, 'lead_dispatcher'::text, 'manager'::text]))));
ALTER TABLE dispatch_team_members ADD CONSTRAINT dispatch_team_members_pkey PRIMARY KEY (id);
ALTER TABLE dispatch_teams ADD CONSTRAINT dispatch_teams_pkey PRIMARY KEY (id);
ALTER TABLE driver_home_status ADD CONSTRAINT driver_home_status_state_check CHECK ((state = ANY (ARRAY['home'::text, 'road'::text])));
ALTER TABLE driver_home_status ADD CONSTRAINT driver_home_status_pkey PRIMARY KEY (group_id);
ALTER TABLE driver_location_checkins ADD CONSTRAINT driver_location_checkin_response_check CHECK (((driver_response IS NULL) OR (driver_response = ANY (ARRAY['yes'::text, 'no'::text, 'checked_in'::text, 'checked_out'::text]))));
ALTER TABLE driver_location_checkins ADD CONSTRAINT driver_location_checkin_status_check CHECK ((status = ANY (ARRAY['awaiting_response'::text, 'answered'::text, 'checked_in'::text, 'completed'::text, 'expired'::text])));
ALTER TABLE driver_location_checkins ADD CONSTRAINT driver_location_checkin_stop_type_check CHECK ((stop_type = ANY (ARRAY['shipper'::text, 'receiver'::text])));
ALTER TABLE driver_location_checkins ADD CONSTRAINT driver_location_checkins_pkey PRIMARY KEY (id);
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_interval_check CHECK (((interval_minutes >= 1) AND (interval_minutes <= 1440)));
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_phase_check CHECK (((load_phase IS NULL) OR (load_phase = ANY (ARRAY['heading_pickup'::text, 'heading_delivery'::text, 'unknown'::text]))));
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_radius_check CHECK (((checkin_radius_miles >= (1)::numeric) AND (checkin_radius_miles <= (100)::numeric)));
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_stop_type_check CHECK (((target_stop_type IS NULL) OR (target_stop_type = ANY (ARRAY['shipper'::text, 'receiver'::text]))));
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_monitors_pkey PRIMARY KEY (id);
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_monitors_group_id_key UNIQUE (group_id);
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_backfill_confidence_check CHECK (((backfill_confidence IS NULL) OR ((backfill_confidence >= 0) AND (backfill_confidence <= 100))));
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_driver_type_check CHECK (((driver_type IS NULL) OR (driver_type = ANY (ARRAY['owner'::text, 'company_driver'::text]))));
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_language_check CHECK (((language)::text = ANY ((ARRAY['en'::character varying, 'ru'::character varying, 'uz'::character varying])::text[])));
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text])));
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_pkey PRIMARY KEY (id);
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_group_id_unique UNIQUE (group_id);
ALTER TABLE driver_road_history ADD CONSTRAINT driver_road_history_pkey PRIMARY KEY (id);
ALTER TABLE drivers ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);
ALTER TABLE drivers ADD CONSTRAINT drivers_telegram_user_id_key UNIQUE (telegram_user_id);
ALTER TABLE duplicate_unit_reports ADD CONSTRAINT duplicate_unit_reports_report_type_check CHECK ((report_type = ANY (ARRAY['duplicate_unit'::text, 'name_mismatch'::text, 'ambiguous_match'::text])));
ALTER TABLE duplicate_unit_reports ADD CONSTRAINT duplicate_unit_reports_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'serious'::text])));
ALTER TABLE duplicate_unit_reports ADD CONSTRAINT duplicate_unit_reports_status_check CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text])));
ALTER TABLE duplicate_unit_reports ADD CONSTRAINT duplicate_unit_reports_pkey PRIMARY KEY (id);
ALTER TABLE duplicate_unit_reports ADD CONSTRAINT duplicate_unit_reports_unit_number_report_type_key UNIQUE (unit_number, report_type);
ALTER TABLE eld_settings ADD CONSTRAINT eld_settings_id_check CHECK ((id = 1));
ALTER TABLE eld_settings ADD CONSTRAINT eld_settings_pkey PRIMARY KEY (id);
ALTER TABLE employee_birthday_settings ADD CONSTRAINT employee_birthday_settings_id_check CHECK ((id = 1));
ALTER TABLE employee_birthday_settings ADD CONSTRAINT employee_birthday_settings_send_hour_check CHECK (((send_hour >= 0) AND (send_hour <= 23)));
ALTER TABLE employee_birthday_settings ADD CONSTRAINT employee_birthday_settings_send_minute_check CHECK (((send_minute >= 0) AND (send_minute <= 59)));
ALTER TABLE employee_birthday_settings ADD CONSTRAINT employee_birthday_settings_pkey PRIMARY KEY (id);
ALTER TABLE employee_birthdays ADD CONSTRAINT employee_birthdays_pkey PRIMARY KEY (id);
ALTER TABLE employee_birthdays ADD CONSTRAINT employee_birthdays_first_name_last_name_key UNIQUE (first_name, last_name);
ALTER TABLE employee_votes ADD CONSTRAINT employee_votes_pkey PRIMARY KEY (id);
ALTER TABLE employee_votes ADD CONSTRAINT employee_votes_poll_id_telegram_user_id_key UNIQUE (poll_id, telegram_user_id);
ALTER TABLE employee_votes_options ADD CONSTRAINT employee_votes_options_pkey PRIMARY KEY (id);
ALTER TABLE employee_votes_polls ADD CONSTRAINT employee_votes_polls_pkey PRIMARY KEY (id);
ALTER TABLE facebook_connect_sessions ADD CONSTRAINT facebook_connect_sessions_pkey PRIMARY KEY (id);
ALTER TABLE facebook_connect_sessions ADD CONSTRAINT facebook_connect_sessions_oauth_state_key UNIQUE (oauth_state);
ALTER TABLE facebook_connect_sessions ADD CONSTRAINT facebook_connect_sessions_session_token_key UNIQUE (session_token);
ALTER TABLE facebook_lead_auto_message_rules ADD CONSTRAINT facebook_lead_auto_message_rules_pkey PRIMARY KEY (id);
ALTER TABLE facebook_lead_auto_message_settings ADD CONSTRAINT facebook_lead_auto_message_settings_pkey PRIMARY KEY (id);
ALTER TABLE facebook_lead_sms_mirrors ADD CONSTRAINT facebook_lead_sms_mirrors_pkey PRIMARY KEY (id);
ALTER TABLE facebook_lead_sms_mirrors ADD CONSTRAINT facebook_lead_sms_mirrors_telegram_chat_id_telegram_message_key UNIQUE (telegram_chat_id, telegram_message_id);
ALTER TABLE facebook_page_connections ADD CONSTRAINT facebook_page_connections_pkey PRIMARY KEY (id);
ALTER TABLE facebook_page_connections ADD CONSTRAINT facebook_page_connections_page_id_key UNIQUE (page_id);
ALTER TABLE facebook_seen_senders ADD CONSTRAINT facebook_seen_senders_pkey PRIMARY KEY (page_id, sender_id);
ALTER TABLE facebook_webhook_events ADD CONSTRAINT facebook_webhook_events_pkey PRIMARY KEY (id);
ALTER TABLE facebook_webhook_events ADD CONSTRAINT facebook_webhook_events_event_key_key UNIQUE (event_key);
ALTER TABLE fuel_monitor_inbox ADD CONSTRAINT fuel_monitor_inbox_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'picked_up'::text])));
ALTER TABLE fuel_monitor_inbox ADD CONSTRAINT fuel_monitor_inbox_pkey PRIMARY KEY (id);
ALTER TABLE fuel_monitor_inbox ADD CONSTRAINT fuel_monitor_inbox_group_id_message_id_key UNIQUE (group_id, message_id);
ALTER TABLE fuel_stop_alerts ADD CONSTRAINT fuel_stop_alerts_status_check CHECK ((status = ANY (ARRAY['watching'::text, 'notified'::text, 'expired'::text, 'error'::text])));
ALTER TABLE fuel_stop_alerts ADD CONSTRAINT fuel_stop_alerts_pkey PRIMARY KEY (id);
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_check_interval_seconds_check CHECK (((check_interval_seconds >= 30) AND (check_interval_seconds <= 3600)));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_deviation_threshold_meters_check CHECK (((deviation_threshold_meters >= 10) AND (deviation_threshold_meters <= 20000)));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_id_check CHECK ((id = 1));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_off_route_grace_checks_check CHECK (((off_route_grace_checks >= 1) AND (off_route_grace_checks <= 20)));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_parked_speed_mph_check CHECK (((parked_speed_mph >= 0) AND (parked_speed_mph <= 60)));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_stale_gps_minutes_check CHECK (((stale_gps_minutes >= 1) AND (stale_gps_minutes <= 240)));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_warning_cooldown_minutes_check CHECK (((warning_cooldown_minutes >= 1) AND (warning_cooldown_minutes <= 1440)));
ALTER TABLE gmaps_settings ADD CONSTRAINT gmaps_settings_pkey PRIMARY KEY (id);
ALTER TABLE group_members ADD CONSTRAINT group_members_pkey PRIMARY KEY (group_id, telegram_user_id);
ALTER TABLE group_pinned_messages ADD CONSTRAINT group_pinned_messages_pkey PRIMARY KEY (id);
ALTER TABLE group_pinned_messages ADD CONSTRAINT group_pinned_messages_group_id_key UNIQUE (group_id);
ALTER TABLE group_recent_loads ADD CONSTRAINT group_recent_loads_pkey PRIMARY KEY (id);
ALTER TABLE group_recent_loads ADD CONSTRAINT group_recent_loads_group_id_telegram_message_id_key UNIQUE (group_id, telegram_message_id);
ALTER TABLE groups ADD CONSTRAINT groups_pkey PRIMARY KEY (id);
ALTER TABLE groups ADD CONSTRAINT groups_telegram_group_id_key UNIQUE (telegram_group_id);
ALTER TABLE home_time_requests ADD CONSTRAINT home_time_requests_source_check CHECK ((source = ANY (ARRAY['telegram'::text, 'manual'::text])));
ALTER TABLE home_time_requests ADD CONSTRAINT home_time_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'cancelled'::text, 'awaiting_dates'::text])));
ALTER TABLE home_time_requests ADD CONSTRAINT home_time_requests_pkey PRIMARY KEY (id);
ALTER TABLE home_time_settings ADD CONSTRAINT home_time_settings_home_allowance_days_check CHECK (((home_allowance_days >= 1) AND (home_allowance_days <= 60)));
ALTER TABLE home_time_settings ADD CONSTRAINT home_time_settings_id_check CHECK ((id = 1));
ALTER TABLE home_time_settings ADD CONSTRAINT home_time_settings_road_allowance_weeks_check CHECK (((road_allowance_weeks >= 1) AND (road_allowance_weeks <= 52)));
ALTER TABLE home_time_settings ADD CONSTRAINT home_time_settings_pkey PRIMARY KEY (id);
ALTER TABLE leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id);
ALTER TABLE leads ADD CONSTRAINT leads_source_external_id_key UNIQUE (source, external_id);
ALTER TABLE message_group_settings ADD CONSTRAINT message_group_settings_id_check CHECK ((id = 1));
ALTER TABLE message_group_settings ADD CONSTRAINT message_group_settings_pkey PRIMARY KEY (id);
ALTER TABLE mileage_bonus_notifications ADD CONSTRAINT mileage_bonus_notifications_action_check CHECK ((action_state = ANY (ARRAY['idle'::text, 'resending'::text, 'disregarding'::text])));
ALTER TABLE mileage_bonus_notifications ADD CONSTRAINT mileage_bonus_notifications_delivery_check CHECK ((delivery_state = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text])));
ALTER TABLE mileage_bonus_notifications ADD CONSTRAINT mileage_bonus_notifications_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'rejected'::text, 'disregarded'::text])));
ALTER TABLE mileage_bonus_notifications ADD CONSTRAINT mileage_bonus_notifications_pkey PRIMARY KEY (id);
ALTER TABLE mileage_bonus_notifications ADD CONSTRAINT mileage_bonus_notifications_unique UNIQUE (driver_normalized_name, threshold_miles);
ALTER TABLE mileage_bonus_progress ADD CONSTRAINT mileage_bonus_progress_pkey PRIMARY KEY (id);
ALTER TABLE mileage_bonus_progress ADD CONSTRAINT mileage_bonus_progress_driver_normalized_name_key UNIQUE (driver_normalized_name);
ALTER TABLE mileage_bonus_runs ADD CONSTRAINT mileage_bonus_runs_mode_check CHECK ((mode = ANY (ARRAY['notify'::text, 'refresh'::text])));
ALTER TABLE mileage_bonus_runs ADD CONSTRAINT mileage_bonus_runs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'succeeded'::text, 'failed'::text])));
ALTER TABLE mileage_bonus_runs ADD CONSTRAINT mileage_bonus_runs_pkey PRIMARY KEY (id);
ALTER TABLE mileage_bonus_runs ADD CONSTRAINT mileage_bonus_runs_run_key_key UNIQUE (run_key);
ALTER TABLE option_translations ADD CONSTRAINT option_translations_pkey PRIMARY KEY (id);
ALTER TABLE option_translations ADD CONSTRAINT option_translations_option_id_language_key UNIQUE (option_id, language);
ALTER TABLE options ADD CONSTRAINT options_pkey PRIMARY KEY (id);
ALTER TABLE question_media ADD CONSTRAINT question_media_pkey PRIMARY KEY (id);
ALTER TABLE question_translations ADD CONSTRAINT question_translations_pkey PRIMARY KEY (id);
ALTER TABLE question_translations ADD CONSTRAINT question_translations_question_id_language_key UNIQUE (question_id, language);
ALTER TABLE questions ADD CONSTRAINT questions_pkey PRIMARY KEY (id);
ALTER TABLE raise_otp ADD CONSTRAINT raise_otp_contact_type_check CHECK ((contact_type = ANY (ARRAY['email'::text, 'phone'::text])));
ALTER TABLE raise_otp ADD CONSTRAINT raise_otp_pkey PRIMARY KEY (id);
ALTER TABLE raise_round_picks ADD CONSTRAINT raise_round_picks_pkey PRIMARY KEY (id);
ALTER TABLE raise_round_submissions ADD CONSTRAINT raise_round_submissions_contact_type_check CHECK ((contact_type = ANY (ARRAY['email'::text, 'phone'::text])));
ALTER TABLE raise_round_submissions ADD CONSTRAINT raise_round_submissions_pkey PRIMARY KEY (id);
ALTER TABLE raise_round_submissions ADD CONSTRAINT raise_round_submissions_round_id_team_id_key UNIQUE (round_id, team_id);
ALTER TABLE raise_rounds ADD CONSTRAINT raise_rounds_status_check CHECK ((status = ANY (ARRAY['open'::text, 'closed'::text])));
ALTER TABLE raise_rounds ADD CONSTRAINT raise_rounds_pkey PRIMARY KEY (id);
ALTER TABLE raise_rounds ADD CONSTRAINT raise_rounds_access_token_key UNIQUE (access_token);
ALTER TABLE raise_settings ADD CONSTRAINT raise_settings_id_check CHECK ((id = 1));
ALTER TABLE raise_settings ADD CONSTRAINT raise_settings_link_ttl_hours_check CHECK (((link_ttl_hours >= 1) AND (link_ttl_hours <= 720)));
ALTER TABLE raise_settings ADD CONSTRAINT raise_settings_otp_channel_check CHECK ((otp_channel = ANY (ARRAY['gmail'::text, 'ringcentral'::text])));
ALTER TABLE raise_settings ADD CONSTRAINT raise_settings_weekly_day_of_week_check CHECK (((weekly_day_of_week >= 1) AND (weekly_day_of_week <= 7)));
ALTER TABLE raise_settings ADD CONSTRAINT raise_settings_pkey PRIMARY KEY (id);
ALTER TABLE recruiters ADD CONSTRAINT recruiters_pkey PRIMARY KEY (id);
ALTER TABLE recruiters ADD CONSTRAINT recruiters_phone_number_normalized_key UNIQUE (phone_number_normalized);
ALTER TABLE responses ADD CONSTRAINT responses_pkey PRIMARY KEY (id);
ALTER TABLE ringcentral_calls ADD CONSTRAINT ringcentral_calls_pkey PRIMARY KEY (id);
ALTER TABLE ringcentral_settings ADD CONSTRAINT ringcentral_settings_id_check CHECK ((id = 1));
ALTER TABLE ringcentral_settings ADD CONSTRAINT ringcentral_settings_poll_minutes_check CHECK (((poll_minutes >= 1) AND (poll_minutes <= 1440)));
ALTER TABLE ringcentral_settings ADD CONSTRAINT ringcentral_settings_pkey PRIMARY KEY (id);
ALTER TABLE route_assignments ADD CONSTRAINT route_assignments_status_check CHECK ((status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text])));
ALTER TABLE route_assignments ADD CONSTRAINT route_assignments_pkey PRIMARY KEY (id);
ALTER TABLE route_monitor_events ADD CONSTRAINT route_monitor_events_pkey PRIMARY KEY (id);
ALTER TABLE safety_event_music_assets ADD CONSTRAINT safety_event_music_assets_duration_seconds_check CHECK (((duration_seconds IS NULL) OR (duration_seconds >= (0)::numeric)));
ALTER TABLE safety_event_music_assets ADD CONSTRAINT safety_event_music_assets_file_size_bytes_check CHECK ((file_size_bytes >= 0));
ALTER TABLE safety_event_music_assets ADD CONSTRAINT safety_event_music_assets_storage_kind_check CHECK ((storage_kind = ANY (ARRAY['db_bytea'::text, 'filesystem'::text, 'object_storage'::text])));
ALTER TABLE safety_event_music_assets ADD CONSTRAINT safety_event_music_assets_pkey PRIMARY KEY (id);
ALTER TABLE safety_event_video_jobs ADD CONSTRAINT safety_event_video_jobs_music_trim_mode_check CHECK (((music_trim_mode IS NULL) OR (music_trim_mode = ANY (ARRAY['trim'::text, 'loop'::text, 'once'::text]))));
ALTER TABLE safety_event_video_jobs ADD CONSTRAINT safety_event_video_jobs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text, 'fallback_sent'::text, 'skipped'::text])));
ALTER TABLE safety_event_video_jobs ADD CONSTRAINT safety_event_video_jobs_video_source_check CHECK (((video_source IS NULL) OR (video_source = ANY (ARRAY['immediate'::text, 'backfill'::text]))));
ALTER TABLE safety_event_video_jobs ADD CONSTRAINT safety_event_video_jobs_pkey PRIMARY KEY (id);
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_fade_in_seconds_check CHECK (((fade_in_seconds >= (0)::numeric) AND (fade_in_seconds <= (60)::numeric)));
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_fade_out_seconds_check CHECK (((fade_out_seconds >= (0)::numeric) AND (fade_out_seconds <= (60)::numeric)));
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_id_check CHECK ((id = 1));
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_max_video_seconds_check CHECK (((max_video_seconds >= 0) AND (max_video_seconds <= 3600)));
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_music_volume_check CHECK (((music_volume >= (0)::numeric) AND (music_volume <= (2)::numeric)));
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_pkey PRIMARY KEY (id);
ALTER TABLE samsara_event_deliveries ADD CONSTRAINT samsara_event_deliveries_pkey PRIMARY KEY (event_id, target_chat_id);
ALTER TABLE samsara_poll_state ADD CONSTRAINT samsara_poll_state_pkey PRIMARY KEY (key);
ALTER TABLE samsara_processed_events ADD CONSTRAINT samsara_processed_events_pkey PRIMARY KEY (id);
ALTER TABLE scheduled_messages ADD CONSTRAINT scheduled_messages_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text, 'cancelled'::text])));
ALTER TABLE scheduled_messages ADD CONSTRAINT scheduled_messages_pkey PRIMARY KEY (id);
ALTER TABLE sender_role_consensus ADD CONSTRAINT sender_role_consensus_pkey PRIMARY KEY (group_id, telegram_user_id);
ALTER TABLE service_runs ADD CONSTRAINT service_runs_pkey PRIMARY KEY (id);
ALTER TABLE service_runs ADD CONSTRAINT service_runs_service_name_run_key_key UNIQUE (service_name, run_key);

-- ── Foreign keys ────────────────────────────────────────────────────
ALTER TABLE ai_insights ADD CONSTRAINT ai_insights_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE ai_insights ADD CONSTRAINT ai_insights_report_id_fkey FOREIGN KEY (report_id) REFERENCES ai_reports(id) ON DELETE CASCADE;
ALTER TABLE ai_reports ADD CONSTRAINT ai_reports_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE broadcast_button_clicks ADD CONSTRAINT broadcast_button_clicks_broadcast_id_fkey FOREIGN KEY (broadcast_id) REFERENCES broadcasts(id) ON DELETE CASCADE;
ALTER TABLE broadcast_deliveries ADD CONSTRAINT broadcast_deliveries_broadcast_id_fkey FOREIGN KEY (broadcast_id) REFERENCES broadcasts(id) ON DELETE CASCADE;
ALTER TABLE chat_logs ADD CONSTRAINT chat_logs_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE chat_message_annotations ADD CONSTRAINT chat_message_annotations_chat_log_id_fkey FOREIGN KEY (chat_log_id) REFERENCES chat_logs(id) ON DELETE CASCADE;
ALTER TABLE datatruck_document_deliveries ADD CONSTRAINT datatruck_document_deliveries_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE dispatch_eta_updates ADD CONSTRAINT dispatch_eta_updates_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE dispatch_team_drivers ADD CONSTRAINT dispatch_team_drivers_driver_profile_id_fkey FOREIGN KEY (driver_profile_id) REFERENCES driver_profiles(id) ON DELETE SET NULL;
ALTER TABLE dispatch_team_drivers ADD CONSTRAINT dispatch_team_drivers_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE dispatch_team_drivers ADD CONSTRAINT dispatch_team_drivers_team_id_fkey FOREIGN KEY (team_id) REFERENCES dispatch_teams(id) ON DELETE CASCADE;
ALTER TABLE dispatch_team_members ADD CONSTRAINT dispatch_team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES dispatch_teams(id) ON DELETE CASCADE;
ALTER TABLE driver_home_status ADD CONSTRAINT driver_home_status_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE driver_location_checkins ADD CONSTRAINT driver_location_checkins_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE driver_location_checkins ADD CONSTRAINT driver_location_checkins_monitor_id_fkey FOREIGN KEY (monitor_id) REFERENCES driver_location_monitors(id) ON DELETE CASCADE;
ALTER TABLE driver_location_monitors ADD CONSTRAINT driver_location_monitors_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE driver_profiles ADD CONSTRAINT driver_profiles_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE driver_road_history ADD CONSTRAINT driver_road_history_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE employee_votes ADD CONSTRAINT employee_votes_option_id_fkey FOREIGN KEY (option_id) REFERENCES employee_votes_options(id) ON DELETE CASCADE;
ALTER TABLE employee_votes ADD CONSTRAINT employee_votes_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES employee_votes_polls(id) ON DELETE CASCADE;
ALTER TABLE employee_votes_options ADD CONSTRAINT employee_votes_options_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE employee_votes_options ADD CONSTRAINT employee_votes_options_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES employee_votes_polls(id) ON DELETE CASCADE;
ALTER TABLE facebook_connect_sessions ADD CONSTRAINT facebook_connect_sessions_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE facebook_lead_auto_message_rules ADD CONSTRAINT facebook_lead_auto_message_rules_settings_id_fkey FOREIGN KEY (settings_id) REFERENCES facebook_lead_auto_message_settings(id) ON DELETE CASCADE;
ALTER TABLE facebook_page_connections ADD CONSTRAINT facebook_page_connections_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE fuel_monitor_inbox ADD CONSTRAINT fuel_monitor_inbox_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES fuel_stop_alerts(id) ON DELETE SET NULL;
ALTER TABLE fuel_monitor_inbox ADD CONSTRAINT fuel_monitor_inbox_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE fuel_stop_alerts ADD CONSTRAINT fuel_stop_alerts_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE group_members ADD CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE group_pinned_messages ADD CONSTRAINT group_pinned_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE group_recent_loads ADD CONSTRAINT group_recent_loads_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE home_time_requests ADD CONSTRAINT home_time_requests_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE option_translations ADD CONSTRAINT option_translations_option_id_fkey FOREIGN KEY (option_id) REFERENCES options(id) ON DELETE CASCADE;
ALTER TABLE options ADD CONSTRAINT options_question_id_fkey FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE;
ALTER TABLE question_media ADD CONSTRAINT question_media_question_id_fkey FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE;
ALTER TABLE question_translations ADD CONSTRAINT question_translations_question_id_fkey FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE;
ALTER TABLE raise_otp ADD CONSTRAINT raise_otp_round_id_fkey FOREIGN KEY (round_id) REFERENCES raise_rounds(id) ON DELETE CASCADE;
ALTER TABLE raise_otp ADD CONSTRAINT raise_otp_team_id_fkey FOREIGN KEY (team_id) REFERENCES dispatch_teams(id) ON DELETE SET NULL;
ALTER TABLE raise_round_picks ADD CONSTRAINT raise_round_picks_round_id_fkey FOREIGN KEY (round_id) REFERENCES raise_rounds(id) ON DELETE CASCADE;
ALTER TABLE raise_round_picks ADD CONSTRAINT raise_round_picks_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES raise_round_submissions(id) ON DELETE CASCADE;
ALTER TABLE raise_round_picks ADD CONSTRAINT raise_round_picks_team_id_fkey FOREIGN KEY (team_id) REFERENCES dispatch_teams(id) ON DELETE CASCADE;
ALTER TABLE raise_round_submissions ADD CONSTRAINT raise_round_submissions_round_id_fkey FOREIGN KEY (round_id) REFERENCES raise_rounds(id) ON DELETE CASCADE;
ALTER TABLE raise_round_submissions ADD CONSTRAINT raise_round_submissions_team_id_fkey FOREIGN KEY (team_id) REFERENCES dispatch_teams(id) ON DELETE CASCADE;
ALTER TABLE responses ADD CONSTRAINT responses_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE;
ALTER TABLE responses ADD CONSTRAINT responses_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE responses ADD CONSTRAINT responses_option_id_fkey FOREIGN KEY (option_id) REFERENCES options(id) ON DELETE CASCADE;
ALTER TABLE responses ADD CONSTRAINT responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE;
ALTER TABLE ringcentral_calls ADD CONSTRAINT ringcentral_calls_recruiter_id_fkey FOREIGN KEY (recruiter_id) REFERENCES recruiters(id) ON DELETE SET NULL;
ALTER TABLE route_assignments ADD CONSTRAINT route_assignments_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE route_monitor_events ADD CONSTRAINT route_monitor_events_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES route_assignments(id) ON DELETE CASCADE;
ALTER TABLE safety_event_video_jobs ADD CONSTRAINT safety_event_video_jobs_music_asset_id_fkey FOREIGN KEY (music_asset_id) REFERENCES safety_event_music_assets(id) ON DELETE SET NULL;
ALTER TABLE safety_event_video_settings ADD CONSTRAINT safety_event_video_settings_active_music_asset_id_fkey FOREIGN KEY (active_music_asset_id) REFERENCES safety_event_music_assets(id) ON DELETE SET NULL;
ALTER TABLE sender_role_consensus ADD CONSTRAINT sender_role_consensus_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;

-- ── Indexes (non-constraint) ────────────────────────────────────────
CREATE INDEX idx_ai_insights_group_id ON public.ai_insights USING btree (group_id);
CREATE INDEX idx_ai_insights_kind_severity ON public.ai_insights USING btree (kind, severity DESC);
CREATE INDEX idx_ai_insights_report_id ON public.ai_insights USING btree (report_id);
CREATE INDEX idx_ai_insights_status ON public.ai_insights USING btree (status);
CREATE INDEX idx_ai_reports_group_id ON public.ai_reports USING btree (group_id);
CREATE INDEX idx_ai_reports_status_generated_at ON public.ai_reports USING btree (status, generated_at DESC);
CREATE INDEX idx_bot_sent_messages_forward_lookup ON public.bot_sent_messages USING btree (sent_at DESC, telegram_chat_id) WHERE (deleted_at IS NULL);
CREATE INDEX idx_bot_sent_messages_recent ON public.bot_sent_messages USING btree (sent_at DESC NULLS LAST, id DESC);
CREATE INDEX idx_bot_users_last_interaction ON public.bot_users USING btree (last_interaction_at DESC);
CREATE INDEX idx_broadcast_button_clicks_broadcast_id ON public.broadcast_button_clicks USING btree (broadcast_id);
CREATE INDEX idx_broadcast_deliveries_broadcast_id ON public.broadcast_deliveries USING btree (broadcast_id);
CREATE INDEX idx_chat_logs_created_at ON public.chat_logs USING btree (created_at DESC);
CREATE INDEX idx_chat_logs_group_id_created_at ON public.chat_logs USING btree (group_id, created_at DESC);
CREATE INDEX idx_annotations_annotated_at ON public.chat_message_annotations USING btree (annotated_at DESC);
CREATE INDEX idx_annotations_intent ON public.chat_message_annotations USING btree (intent);
CREATE INDEX idx_annotations_role ON public.chat_message_annotations USING btree (role_guess);
CREATE INDEX idx_datatruck_document_deliveries_group ON public.datatruck_document_deliveries USING btree (group_id, created_at DESC);
CREATE INDEX idx_datatruck_document_deliveries_status ON public.datatruck_document_deliveries USING btree (status, created_at DESC);
CREATE INDEX idx_dispatch_eta_due ON public.dispatch_eta_updates USING btree (next_run_at) WHERE (enabled = true);
CREATE INDEX idx_dispatch_team_drivers_profile ON public.dispatch_team_drivers USING btree (driver_profile_id) WHERE (driver_profile_id IS NOT NULL);
CREATE INDEX idx_dispatch_team_drivers_team ON public.dispatch_team_drivers USING btree (team_id);
CREATE UNIQUE INDEX uniq_dispatch_active_driver_group ON public.dispatch_team_drivers USING btree (group_id) WHERE (active AND (group_id IS NOT NULL));
CREATE UNIQUE INDEX uniq_dispatch_active_driver_profile ON public.dispatch_team_drivers USING btree (driver_profile_id) WHERE (active AND (driver_profile_id IS NOT NULL));
CREATE INDEX idx_dispatch_team_members_team ON public.dispatch_team_members USING btree (team_id);
CREATE INDEX idx_dispatch_team_members_user_id ON public.dispatch_team_members USING btree (telegram_user_id) WHERE (telegram_user_id IS NOT NULL);
CREATE INDEX idx_dispatch_team_members_username ON public.dispatch_team_members USING btree (telegram_username) WHERE (telegram_username IS NOT NULL);
CREATE INDEX idx_driver_location_checkins_group_created ON public.driver_location_checkins USING btree (group_id, created_at DESC);
CREATE INDEX idx_driver_location_checkins_monitor ON public.driver_location_checkins USING btree (monitor_id, created_at DESC);
CREATE UNIQUE INDEX idx_driver_location_checkins_stop_once ON public.driver_location_checkins USING btree (dedupe_key) WHERE (dedupe_key IS NOT NULL);
CREATE INDEX idx_driver_location_due ON public.driver_location_monitors USING btree (next_run_at) WHERE (enabled = true);
CREATE UNIQUE INDEX idx_driver_profiles_group_id ON public.driver_profiles USING btree (group_id);
CREATE INDEX idx_driver_profiles_language ON public.driver_profiles USING btree (language);
CREATE INDEX idx_driver_profiles_needs_review ON public.driver_profiles USING btree (needs_review) WHERE (needs_review = true);
CREATE INDEX idx_driver_profiles_status ON public.driver_profiles USING btree (status);
CREATE INDEX idx_driver_profiles_unit_number ON public.driver_profiles USING btree (unit_number);
CREATE INDEX idx_driver_road_history_bonus ON public.driver_road_history USING btree (home_arrived_at DESC) WHERE (bonus_usd > (0)::numeric);
CREATE INDEX idx_driver_road_history_group ON public.driver_road_history USING btree (group_id, home_arrived_at DESC);
CREATE INDEX idx_driver_road_history_unposted ON public.driver_road_history USING btree (home_arrived_at) WHERE ((bonus_usd > (0)::numeric) AND (bonus_posted_at IS NULL));
CREATE INDEX idx_duplicate_unit_reports_open ON public.duplicate_unit_reports USING btree (status, last_seen_at DESC) WHERE (status = 'open'::text);
CREATE INDEX idx_employee_votes_option_id ON public.employee_votes USING btree (option_id);
CREATE INDEX idx_employee_votes_options_group ON public.employee_votes_options USING btree (group_id);
CREATE INDEX idx_employee_votes_options_poll ON public.employee_votes_options USING btree (poll_id);
CREATE INDEX idx_facebook_connect_sessions_expires ON public.facebook_connect_sessions USING btree (expires_at);
CREATE INDEX idx_facebook_connect_sessions_group ON public.facebook_connect_sessions USING btree (telegram_group_id, status);
CREATE INDEX idx_facebook_lead_auto_message_rules_settings ON public.facebook_lead_auto_message_rules USING btree (settings_id, sort_order, id);
CREATE INDEX idx_facebook_lead_sms_mirrors_lookup ON public.facebook_lead_sms_mirrors USING btree (telegram_chat_id, telegram_message_id);
CREATE INDEX idx_facebook_page_connections_group ON public.facebook_page_connections USING btree (telegram_group_id, is_active);
CREATE INDEX idx_facebook_webhook_events_page ON public.facebook_webhook_events USING btree (page_id, created_at DESC);
CREATE INDEX idx_facebook_webhook_events_status_retry ON public.facebook_webhook_events USING btree (status, next_retry_at, created_at);
CREATE INDEX idx_fuel_monitor_inbox_alert_id ON public.fuel_monitor_inbox USING btree (alert_id);
CREATE INDEX idx_fuel_monitor_inbox_status_created ON public.fuel_monitor_inbox USING btree (status, created_at DESC);
CREATE INDEX idx_fuel_stop_alerts_due ON public.fuel_stop_alerts USING btree (status, expires_at);
CREATE INDEX idx_fuel_stop_alerts_group ON public.fuel_stop_alerts USING btree (group_id, created_at DESC);
CREATE INDEX idx_fuel_stop_alerts_next_check ON public.fuel_stop_alerts USING btree (status, next_check_at);
CREATE UNIQUE INDEX idx_group_pinned_messages_group_id ON public.group_pinned_messages USING btree (group_id);
CREATE INDEX idx_group_pinned_messages_updated_at ON public.group_pinned_messages USING btree (updated_at DESC);
CREATE INDEX idx_group_recent_loads_group_created ON public.group_recent_loads USING btree (group_id, created_at DESC);
CREATE INDEX idx_groups_samsara_vehicle_id ON public.groups USING btree (samsara_vehicle_id) WHERE (samsara_vehicle_id IS NOT NULL);
CREATE INDEX idx_groups_type_active ON public.groups USING btree (group_type, active);
CREATE INDEX idx_home_time_requests_group ON public.home_time_requests USING btree (group_id, requested_at DESC);
CREATE INDEX idx_home_time_requests_status ON public.home_time_requests USING btree (status, requested_at DESC);
CREATE INDEX idx_leads_created_at ON public.leads USING btree (created_at DESC);
CREATE INDEX idx_leads_source_created ON public.leads USING btree (source, created_at DESC);
CREATE INDEX idx_mileage_bonus_notifications_created ON public.mileage_bonus_notifications USING btree (created_at DESC);
CREATE INDEX idx_mileage_bonus_notifications_status ON public.mileage_bonus_notifications USING btree (status);
CREATE INDEX idx_mileage_bonus_progress_total ON public.mileage_bonus_progress USING btree (total_miles DESC);
CREATE INDEX idx_mileage_bonus_runs_started ON public.mileage_bonus_runs USING btree (started_at DESC);
CREATE INDEX idx_mileage_bonus_runs_status ON public.mileage_bonus_runs USING btree (status, lease_expires_at, next_retry_at);
CREATE INDEX idx_options_question_id ON public.options USING btree (question_id);
CREATE INDEX idx_question_media_question_id ON public.question_media USING btree (question_id);
CREATE INDEX idx_raise_otp_lookup ON public.raise_otp USING btree (round_id, contact, created_at DESC);
CREATE INDEX idx_raise_otp_team_id ON public.raise_otp USING btree (team_id);
CREATE INDEX idx_raise_round_picks_round ON public.raise_round_picks USING btree (round_id);
CREATE INDEX idx_raise_round_picks_submission ON public.raise_round_picks USING btree (submission_id);
CREATE INDEX idx_raise_round_picks_team ON public.raise_round_picks USING btree (team_id);
CREATE INDEX idx_raise_round_submissions_team ON public.raise_round_submissions USING btree (team_id);
CREATE INDEX idx_raise_rounds_status ON public.raise_rounds USING btree (status, created_at DESC);
CREATE INDEX idx_responses_answered_at ON public.responses USING btree (answered_at DESC);
CREATE INDEX idx_responses_group_id_answered_at ON public.responses USING btree (group_id, answered_at DESC);
CREATE INDEX idx_responses_option_id ON public.responses USING btree (option_id);
CREATE INDEX idx_responses_question_id ON public.responses USING btree (question_id);
CREATE UNIQUE INDEX idx_unique_driver_question ON public.responses USING btree (driver_id, question_id);
CREATE INDEX idx_ringcentral_calls_recruiter_time ON public.ringcentral_calls USING btree (recruiter_id, call_time DESC);
CREATE INDEX idx_ringcentral_calls_time ON public.ringcentral_calls USING btree (call_time DESC);
CREATE INDEX idx_route_assignments_active ON public.route_assignments USING btree (status, updated_at DESC) WHERE (status = 'active'::text);
CREATE INDEX idx_route_assignments_group ON public.route_assignments USING btree (group_id, created_at DESC);
CREATE UNIQUE INDEX uniq_route_assignments_telegram_message ON public.route_assignments USING btree (telegram_chat_id, telegram_message_id) WHERE ((telegram_chat_id IS NOT NULL) AND (telegram_message_id IS NOT NULL));
CREATE INDEX idx_route_monitor_events_assignment ON public.route_monitor_events USING btree (assignment_id, created_at DESC);
CREATE INDEX idx_safety_event_music_created ON public.safety_event_music_assets USING btree (created_at DESC);
CREATE UNIQUE INDEX uniq_safety_event_music_active ON public.safety_event_music_assets USING btree (is_active) WHERE is_active;
CREATE INDEX idx_safety_event_video_jobs_event ON public.safety_event_video_jobs USING btree (samsara_event_id);
CREATE INDEX idx_safety_event_video_jobs_status_created ON public.safety_event_video_jobs USING btree (status, created_at DESC);
CREATE INDEX idx_scheduled_messages_pending_due ON public.scheduled_messages USING btree (scheduled_at) WHERE (status = 'pending'::text);
CREATE INDEX idx_service_runs_ran_at ON public.service_runs USING btree (ran_at DESC);

